[package]
name = "pod-metrics-exporter"
version = "2.0.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11"
reqwest = { version = "0.12.4", features = ["json"] }
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7.4", features = ["http2"] }
serde_json = "1"