apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-metrics-exporter
  labels:
    app: pod-metrics-exporter
spec:
  selector:
    matchLabels:
      app: pod-metrics-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-metrics-exporter
    spec:
      containers:
        - name: pod-metrics-exporter
          # NOTE: This software is not published in public registry, so you need to use our own registry
          # image: pod-metrics-exporter:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 10
            periodSeconds: 1
      serviceAccountName: pod-metrics-exporter-sa

---
apiVersion: v1
kind: Service
metadata:
  name: pod-metrics-exporter-svc
spec:
  selector:
    app: pod-metrics-exporter
  type: ClusterIP
  # type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      # nodePort: 30000

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-metrics-exporter-role
rules:
  - apiGroups:
      - 'metrics.k8s.io'
    resources:
      - pods
    verbs:
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-metrics-exporter-role-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-metrics-exporter-role
subjects:
  - kind: ServiceAccount
    name: pod-metrics-exporter-sa

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-metrics-exporter-sa
